---
name: Bump Version

"on":
  push:
    branches: ['main']
  workflow_dispatch: null # For manual runs

jobs:
  bump-version:
    # Ignore the commits from this action
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: Bump version and make release with commitizen
    # Fix 403 error (https://github.com/softprops/action-gh-release/issues/400)
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: 0

      - name: Bump version and generate changelog
        uses: commitizen-tools/commitizen-action@338bbd841b75aaee6bf5340e1fa12f6ab58ff9ff # master
        with:
          branch: main
          changelog_increment_filename: body.md
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate GitHub Release Notes
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2.6.2
        with:
          body_path: body.md
          tag_name: v${{ env.REVISION }}
